### ISSUE TITLE
Add header only consumption mode

### ISSUE THREAD

**Issue by mborland** [boostorg/charconv#136]
See: https://github.com/boostorg/json#header-only

**Comment by pdimov** [comment]
This isn't a particularly good or useful idea. It's not practical to have a header-only _option_ for this library. Either it should be always header-only, or always compiled.

That's because now every downstream consumer needs to pick a mode, and they all must pick the same mode. E.g. if JSON uses the library in header-only mode, and my code uses JSON, my code (and all its dependencies) also must use header-only mode. And conversely, if JSON uses compiled Charconv, everyone else must, too.

Also, the above link doesn't actually describe header-only, even though it's called such.
